--- !ruby/object:Skin 
skin_name: default
display_name: "Default"
skin_properties: 

  skin_width:  "100%"
  center_block_spacing: "8"
  header_center_display: "true"
  background_img: ""
  header_img: "/legacy/skins//headerbig.png"
  header_height: "90px"
  header_small: "/legacy/skins/ /headersmall.png"
  header_big: "/legacy/skins/ /headerbig.png"
  header_plus: "/legacy/skins/ /headersmall.png"
  
  side_width: "130px"
  blockBorder: "0"
  blockheadpic: "blockhead.png"
  blockheadpicsize: "30"
  valignsideheader: "center"
  
  menupic: "/legacy/skins/ /menubg.png"
  menuheight: "23px"
  menudivider: " | "
  menuspacer: "#ffffff"
  menuspacersize: "0px"
  menugutter: "#ffffff"
  menuguttersize: "0px"
  menuends: ""
  
  page_background_color: "#d4d6d7"
  page_font_family: "Arial, sans-serif"
  page_font_size: "8pt"
  minor_font_color: "#737373"
  link_color: "#0353A2"
  link_accent_color: "#516068"
  link_text_decoration: "none"
  link_accent_text_decoration: "none"
  primary_text_color: "#323237"
  primary_background_color: "#ffffff"
  secondary_text_color: "#000000"
  secondary_background_color: "#e0e3ea"
  user_message_text_color: "#000000"
  user_message_background_color: "#d7dff2"
  header_text_color: "#ffffff"
  header_background_color: "#0353A2"
  header_font_family: "Arial, sans-serif"
  header_font_size: "9pt"
  header_link_color: "#ffffff"
  header_link_accent_color: "#d4d6d7"
  sidebar_text_color: "#323237"
  sidebar_background_color: "#ffffff"
  sidebar_header_text_color: "#000000"
  sidebar_link_color: "#323237"
  sidebar_link_accent_color: "#d4d6d7"
  section_header_text_color: "#000000"
  section_header_background_color: "#ffffff"
  section_header_background_image: "/legacy/skins/newblue/fronthead.png"
  music_micro_entry_background_color: "#e0e1e2"
  music_micro_entry_text_color: "#404040"
  music_article_link_color: "#EC008C"
  music_primary_background_color: "#FFFFFF"
  music_primary_text_color: "#000"
  music_stripe_1_color: "#FFF"
  music_stripe_2_color: "#DDD"
