--- !ruby/object:Skin 
skin_name: default
display_name: "Default"
skin_properties: 
  
  side_header_height: "30px"
  
  page_background_color: "#939697"
  link_color: "#ee2b7b"
  link_accent_color: "#516068"
  primary_text_color: "#323237"
  primary_background_color: "#ffffff"
  secondary_text_color: "#000"
  secondary_background_color: "#DFDFDF"
  subdued_text_color: "#878787"
  user_message_text_color: "#000000"
  user_message_background_color: "#fff"
  user_message_border_color: "#ccc"
  header_text_color: "#fff"
  header_background_color: "#000"
  header_link_color: "#fff"
  header_link_accent_color: "#d4d6d7"
  sidebar_text_color: "#323237"
  sidebar_background_color: "#fff"
  sidebar_header_text_color: "#000"
  sidebar_link_color: "#323237"
  sidebar_link_accent_color: "#ee2b7b"
  section_header_text_color: "#000000"
  section_header_background_color: "#ffffff"
  section_header_background_image: "/legacy/skins/newblack/fronthead.png"
  user_online_color: "#00AA00"
  user_offline_color: "#BF0E00"
  
  minor_font_color: "#737373"
  link_text_decoration: "none"
  link_accent_text_decoration: "none"

  dual_bg1_link_color: "#ee2b7b"
  dual_bg2_link_color: "#ee2b7b"
  dual_bg1_link_accent_color: "#516068"
  dual_bg2_link_accent_color: "#516068"
  
  music_micro_entry_background_color: "#e0e1e2"
  music_micro_entry_text_color: "#404040"
  music_article_link_color: "#EC008C"
  music_primary_background_color: "#FFFFFF"
  music_primary_text_color: "#000"
  music_stripe_1_color: "#FFF"
  music_stripe_2_color: "#DDD"

  page_font_size: "11px"
  minor_font_size: "10px"
  header_font_size: "14px"
  page_header_font_size: "16px"

  page_font_family: "Verdana, Helvetica, Arial, sans-serif"
  header_font_family: "Verdana, Helvetica, Arial, sans-serif"
  
  legacy_font_family: "Arial, sans-serif"
  legacy_body_font_size: "8pt"
  legacy_sidebar_text_color: "#323237"
  legacy_sidebar_background_color: "#fff"
  legacy_sidebar_header_text_color: "#000"
  legacy_sidebar_link_color: "#323237"
  legacy_sidebar_link_accent_color: "#ee2b7b"
  legacy_sidebar_input_border_color: "#d4d6d7"
  
  legacy_header_background_color: "#000"
  legacy_header_text_color: "#fff"
  legacy_header_link_color: "#fff"
  legacy_header_link_accent_color: "#d4d6d7"
  legacy_header_front_text_color: "#000"
  legacy_header_front_background_color: "#fff"
  legacy_header_front_height: "30px"
  
  legacy_alt_header_text_color: "#323237"
  legacy_alt_header_link_color: "#323237"
  legacy_alt_header_link_accent_color: "#fff"
  
  legacy_primary_background_color: "#fff"
  legacy_primary_text_color: "#323237"
  legacy_secondary_background_color: "#dfdfdf"
  legacy_secondary_text_color: "#000"
  
  legacy_link_color: "#ee2b7b"
  legacy_link_accent_color: "#516068"
  
  legacy_footer_color: "#d4d6d7"
  
  legacy_menu_text_color: "#bfbfbf"
  legacy_menu_link_color: "#bfbfbf"
  legacy_menu_link_accent_color: "#dfdfdf"
  
  legacy_forum_new_posts_background_color: "#d6e3ee"
  legacy_forum_new_posts_text_color: "#0353a2"
  legacy_forum_new_posts_link_color: "#af0000"
  legacy_forum_new_posts_link_accent_color: "#516068"
  
  legacy_forum_no_new_posts_background_color: "#d6e3ee"
  legacy_forum_no_new_posts_text_color: "#0353a2"
  legacy_forum_no_new_posts_link_color: "#000"
  legacy_forum_no_new_posts_link_accent_color: "#516068"
  
  legacy_forum_new_thread_link_color: "#ee2b7b"
  legacy_forum_new_thread_link_accent_color: "#516068"
  
  legacy_small_background_color: "#dfdfdf"
  legacy_small_text_color: "#000"
  legacy_small_link_color: "#000"
  legacy_small_link_accent_color: "#3a3a3a"
  
  legacy_user_message_background_color: "#dfdfdf"
  legacy_user_message_text_color: "#000"
  legacy_user_message_link_color: "#000"
  legacy_user_message_link_accent_color: "#3a3a3a"
  
  menuheight: "18px"
