<?

	//format: array( 'splittable' => 'splitcol', 'agregatetable' => false, ...)
	//adding extra tables isn't a problem, as they're ignored
	return array(
		'agesexgroups' => false,
		'archive' => 'userid',
		'blog' => 'userid',
		'blogcomments' => 'bloguserid',
		'blogcommentsunread' => 'userid',
		'bloglastreadfriends' => 'userid',
		'forumcatcollapse' => 'userid',
		'forumcats' => 'userid',
		'foruminvite' => 'userid',
		'forumread' => 'userid',
		'forumupdated' => 'userid',
		'friendevents' => 'userid',
		'friends' => 'userid',
		'friendscomments' => 'userid',
		'gallery' => 'ownerid',
		'gallerypending' => 'userid',
		'gallerypics' => 'userid',
		'globalgrant' => false,
		'ignore' => 'userid',
		'intereststats' => false,
		'internalstatusmessages' => 'userid',
		'locstats' => false,
		'loginlog' => 'userid',
		'msgarchive' => false,
		'msgfolder' => 'userid',
		'msgs' => 'userid',
		'msgtext' => 'userid',
		'msgtickets' => 'userid',
		'observablepermissions' => 'userid',
		'observationpreferences' => 'userid',
		'picbans' => 'userid',
		'pics' => 'userid',
		'picspending' => 'userid',
		'profile' => 'userid',
		'profileblocks' => 'userid',
		'profileviews' => 'userid',
		'sessions' => 'userid',
		'sourcepics' => 'userid',
		'stats' => false,
		'status' => 'userid',
		'typerolemembers' => false,
		'useractivetime' => 'userid',
		'usercomments' => 'userid',
		'usercommentsarchive' => false,
		'usercounter' => 'id',
		'userevents' => 'userid',
		'userfiles' => 'userid',
		'userfileslayout' => 'userid',
		'userhitlog' => 'userid',
		'userinterests' => 'userid',
		'usernames' => 'userid',
		'userpasswords' => 'userid',
		'users' => 'userid',
		'usersearch' => 'userid',
		'videocomments' => 'userid',
		'videofavs' => 'userid',
		'videonavigate' => 'userid',
		'videos' => 'userid',
	);
