<?

	$login=1;

	require_once("include/general.lib.php");

	$uid = $userData['userid'];

	switch($action){
		case "add":
			addSkin();
			//exit

		case "edit":
			if($id = getREQval('id'))
				addSkin($id);//exit
			break;

		case "Add":
			if($data = getREQval('data'))
				insertSkin($data);
			break;

		case "Update":
			$id = getPOSTval('id');
			$data = getPOSTval('data');
			if($id && $data)
				updateSkin($id, $data);
			break;

		case "delete":
			if($id = getREQval('id'))
				deleteSkin($id);
			break;
	}

	listSkins();

///////////////////////

function listSkins(){
	global $uid, $db;

	$db->prepare_query("SELECT id, name FROM profileskins WHERE userid = ? ORDER BY name", $uid);

	$rows = array();
	while($line = $db->fetchrow())
		$rows[$line['id']] = $line['name'];

	incHeader();

	echo "<table align=center>";
	echo "<tr>";
		echo "<td class=header>Title</td>";
		echo "<td class=header></td>";
	echo "</tr>";

	foreach($rows as $id => $name){
		echo "<tr>";
		echo "<td class=body><a class=body href=$_SERVER[PHP_SELF]?action=edit&id=$id>$name</a></td>";
		echo "<td class=body><a class=body href=$_SERVER[PHP_SELF]?action=delete&id=$id>Delete</a></td>";
		echo "</tr>";
	}
	echo "<tr><td class=header colspan=2 align=right><a class=header href=$_SERVER[PHP_SELF]?action=add>Create New Skin</a></td></tr>";
	echo "</table>";

	incFooter();
	exit;
}


function addSkin($id = 0, $data = array()){
	global $data, $uid, $db, $config;

	$headerbg = "#";
	$headertext = "#";
	$headerlink = "#";
	$headerhover = "#";
	$bodybg = "#";
	$bodybg2 = "#";
	$bodytext = "#";
	$bodylink = "#";
	$bodyhover = "#";
//	$votelink = "#";
//	$votehover = "#";
	$online = "#";
	$offline = "#";
	$name = "";

	if($id && !count($data)){
		$db->prepare_query("SELECT name, data FROM profileskins WHERE id = ? && userid = ?", $id, $uid);
		if($db->numrows()){
			$line = $db->fetchrow();
			extract(decodeSkin($line['data']));
			$name = $line['name'];
		}else{
			$data = array();
		}
	}elseif(is_array($data)){
		extract($data);
	}

	incHeader();

	echo "<table align=center width=366><form action=$_SERVER[PHP_SELF] method=post>";

	echo "<tr><td class=body colspan=2 align=center valign=top height=300>";
	echo "<div style=\"position:relative;\">";
	echo "<script src=$config[imgserver]/skins/color.js></script>";
	echo "<script>displayColors();</script>";
	echo "</div>";
	echo "</td></tr>";

	if($id)
		echo "<tr><td class=header colspan=2 align=center>Edit Skin</td></tr>";
	else
		echo "<tr><td class=header colspan=2 align=center>Create a Skin</td></tr>";

	echo "<tr><td class=body>Skin title:</td><td class=body><input type=text class=body name=data[name] value='$name' maxlength=32></td></tr>";
	echo "<tr><td class=body colspan=2>All colours must be in RGB HEX values. They may include, but are not limited to, any colour generated by the colour chart above.</td></tr>";

	echo "<tr><td class=header colspan=2 align=center>Header</td></tr>";
	echo "<tr><td class=body>Background:</td><td class=body><input type=text class=body name=data[headerbg] value='$headerbg' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Text:</td><td class=body><input type=text class=body name=data[headertext] value='$headertext' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Link:</td><td class=body><input type=text class=body name=data[headerlink] value='$headerlink' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Link Hover:</td><td class=body><input type=text class=body name=data[headerhover] value='$headerhover' maxlength=7 size=7></td></tr>";

	echo "<tr><td class=header colspan=2 align=center>Body</td></tr>";
	echo "<tr><td class=body>Background:</td><td class=body><input type=text class=body name=data[bodybg] value='$bodybg' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Alternating Background:</td><td class=body><input type=text class=body name=data[bodybg2] value='$bodybg2' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Text:</td><td class=body><input type=text class=body name=data[bodytext] value='$bodytext' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Link:</td><td class=body><input type=text class=body name=data[bodylink] value='$bodylink' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Link Hover:</td><td class=body><input type=text class=body name=data[bodyhover] value='$bodyhover' maxlength=7 size=7></td></tr>";

	echo "<tr><td class=header colspan=2 align=center>Other</td></tr>";
//	echo "<tr><td class=body>Vote Links:</td><td class=body><input type=text class=body name=data[votelink] value='$votelink' maxlength=7 size=7></td></tr>";
//	echo "<tr><td class=body>Vote Links Hover:</td><td class=body><input type=text class=body name=data[votehover] value='$votehover' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Online:</td><td class=body><input type=text class=body name=data[online] value='$online' maxlength=7 size=7></td></tr>";
	echo "<tr><td class=body>Offline:</td><td class=body><input type=text class=body name=data[offline] value='$offline' maxlength=7 size=7></td></tr>";

	if($id)
		echo "<tr><td class=body align=center colspan=2><input type=hidden name=id value=$id><input class=body type=submit name=action value=Update></td></tr>";
	else
		echo "<tr><td class=body align=center colspan=2><input class=body type=submit name=action value=Add></td></tr>";

	echo "</form></table>";

	incFooter();
	exit;
}

function insertSkin($data){
	global $uid, $db, $msgs;

	$data2 = encodeSkin($data);

	if(!$data2){
		$msgs->addMsg("You must fill out all boxes with valid RGB HEX colors");
		addSkin(0,$data); //exit
	}

	if(empty($data['name'])){
		$msgs->addMsg("You must give it a name");
		addSkin(0,$data); //exit
	}

	$db->prepare_query("INSERT INTO profileskins SET userid = ?, name = ?, data = ?", $uid, $data['name'], $data2);
}

function updateSkin($id, $data){
	global $uid, $db, $msgs, $cache;

	$data2 = encodeSkin($data);

	if(!$data2){
		$msgs->addMsg("You must fill out all boxes with valid RGB HEX colors");
		addSkin($id,$data); //exit
	}

	if(empty($data['name'])){
		$msgs->addMsg("You must give it a name");
		addSkin($id,$data); //exit
	}

	$db->prepare_query("UPDATE profileskins SET name = ?, data = ? WHERE id = ? && userid = ?", $data['name'], $data2, $id, $uid);
	$cache->remove(array($id, "profileskin-$id"));
}

function deleteSkin($id){
	global $db, $uid, $cache;

	$db->prepare_query("DELETE FROM profileskins WHERE id = ? && userid = ?", $id, $uid);
	$cache->remove(array($id, "profileskin-$id"));
}

