
# Code Generated by ZenTest v. 3.4.1
#                 classname: asrt / meth =  ratio%
#                    Friend:    0 /    3 =   0.00%
lib_require :Devutils, 'quiz' unless defined? $ZENTEST and $ZENTEST
require 'core/lib/users/user'
require 'friends/lib/friend'
require 'mocha'
require 'stubba'

class TestFriend < Quiz


	def setup
		@me = User.new
		@me.userid = 1
		@f1 = Friend.new
		@f1.userid = 1
		@f1.friendid = 2
		@f2 = Friend.new
		@f2.userid = 1
		@f2.friendid = 3
		@friends_list = []
		#
		# Stub around :store and :delete 
		#
		Friend.any_instance.stubs(:store).returns(true)
		Friend.any_instance.stubs(:delete).returns(true)
		User.any_instance.stubs(:friends).returns(@friends_list)
		
	end
	def test_user
		# raise NotImplementedError, 'Need to write test_user'
	end

	def test_add
		me = @me
	   add_friends = [@f1,@f2]
		add_friends.each {|f|
				me.add_friend(f.friendid)
		}
		assert_equal(2,me.friends.length)
		assert_equal(add_friends,me.friends)
	end

	def test_remove
		# Setup friends_list to contain 2 friends
		# So that the stub works properly
		@friends_list = [@f1,@f2]
		#		
		me = @me
	   remove_friends = [@f1,@f2]
	
		remove_friends.each {|f|
				me.remove_friend(f.friendid)
		}
		assert_equal(0,me.friends.length)
		assert_equal([],me.friends)
	end
end

# Number of errors detected: 36
